# Generated by Django 6.0.7 on 2026-07-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=20)),
                ('clave', models.CharField(max_length=15, unique=True)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
    ]
