# Generated by Django 6.0.7 on 2026-07-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_trabajo', models.TimeField()),
                ('hora_fin_trabajo', models.TimeField()),
                ('nombre_servicio', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('tiempo_limite_cita', models.IntegerField()),
                ('id_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
