# Generated by Django 6.0.7 on 2026-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='tiempo_limite_cita',
            field=models.CharField(max_length=30),
        ),
    ]
