# Generated by Django 6.0.7 on 2026-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_catalogo_tiempo_limite_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='fondo_img',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
